spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LootGeneratorDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${MAIL_SERVICE_KEY}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 3000
application:
  security:
    jwt:
      secret-key: ${JWT_KEY}
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
  configuration:
    init-test-data: true
api:
  info:
    security:
      scheme:
        name: "bearerAuth"
        type: "bearer"
        format: "JWT"
    title: "Loot Generator API"
    contact:
      name: "Dimitar Todorov"
      email: "d.todorov.vn@gmail.com"
    description: "This API is made to be consumed by Web and Mobile front-end applications"
    version: "v0.1"
springdoc:
  swagger-ui:
    path: /api-docs/swagger.html
  api-docs:
    path: /api-docs
logging:
  level:
    org:
      springframework:
        security: error
google:
  client-id: ${GOOGLE_CLIENT_ID}
server:
  forward-headers-strategy: native