spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LootGeneratorDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: your.smtp.host
    port: 123
    username: your.smtp.username
    password: your.smtp.password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 3000
application:
  security:
    jwt:
      secret-key: QStGaFp2Z294a3pOWSszb2I1OTdoVXRQNGY2SE41aFVORDV1SXBSbTZrclRFRU1sTmRuK3hoWWJJaVIxMzlvYw==
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
