name: CI/CD for Spring Boot API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
      - name: Debug environment variables
        run: |
          echo "TOMCAT_HOST=$TOMCAT_HOST"
          echo "TOMCAT_PORT=$TOMCAT_PORT"

      - name: Deploy to remote Tomcat
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
        run: |
          curl -v -u $TOMCAT_USER:$TOMCAT_PASSWORD \
          --upload-file *.war \
          https://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/your-app-name&update=true
